[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Railway will automatically expose the PORT that your app listens on
